apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
    environment: production
spec:
  containers: #list/array of containers
    - name: myapp-container
      image: nginx 


# kubectl create -f nginx-pod.yml